fix indentation in workflow

diff --git a/.github/workflows/instagram_feed.yml b/.github/workflows/instagram_feed.yml
--- a/.github/workflows/instagram_feed.yml
+++ b/.github/workflows/instagram_feed.yml
@@ -51,6 +51,6 @@ jobs:
           set -o pipefail
           python scraping/instagram_feed.py | tee scraper_output.txt
           if grep -q "Oops, an error occurred." scraper_output.txt; then
-          echo "Error detected in scraper output."
-          exit 1
-        fi
+            echo "Error detected in scraper output."
+            exit 1
+          fi
